workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}
matrix:
  GO_VERSION:
    - latest
    - 1.7
pipeline:
  build:
    image: golang:${GO_VERSION}
    environment:
      - GOPATH=/go
      - GO15VENDOREXPERIMENT=1
    commands:
      - env
      - export PATH=$PATH:$GOPATH/bin
      - go get -v -x
      - go test -v

