language: go
go:
- 1.3
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8rc3
- tip
before_install:
- go get -u -v github.com/mattn/goveralls
script:
- $HOME/gopath/bin/goveralls -service=travis-ci
- go test -v
- go tool vet -v -all .
branches:
  only:
  - master
notifications:
  irc:
    channels:
    - irc.byteirc.org#L
    template:
    - "%{repository} #%{build_number} %{branch}/%{commit}: %{author} -- %{message}
      %{build_url}"
    on_success: change
    on_failure: change
    skip_join: false
